### PR TITLE
Added rotate vector function and test

### PR DESCRIPTION
**Pull request by maxschommer**
- Added a function to rotate a 3D vector by a quaternion

### CODE REVIEW

**Comment by westphae** [comment]
Hi. Looks like a good idea. Your RotateVec3 function might also be implemented as a method of the Vec3 struct, i.e. func (vIn Vec3) Rotate(q Quaternion) (vOut Vec3).  Then rotations can be composed like V.Rotate(Q1).Rotate(Q2).  If you'd like to implement that, let me know; otherwise I'll go ahead and merge this and implement it myself.

**Comment by maxschommer** [comment]
That sounds like a great idea! I'll try to get that done this weekend.

**Comment by maxschommer** [comment]
Sorry about the delay, but I added the Rotate method to Vec3 as you suggested, great idea!

**Comment by westphae** [comment]
Looks great!  Merged.  Thank you!

**Pull request merged**
